spring:
  profiles:
    active: dev
server:
  application:
    name: mayiservice
  servlet:
    context-path: /mayi
#endpoints:
#  mappings:
#    sensitive: false

management:
  health:
    db:
      enabled: false
    mail:
      enabled: false
  security:
    basic:
      enabled: false
    path: /mayi
  server:
    port: 10000
    servlet:
      context-path: /mayi
